language: php
php:
  - "5.4"
  - "5.3"
env:
  - DB=mysql
  - DB=postgres
before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'DROP DATABASE IF EXISTS beaconframework_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE beaconframework_tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS beaconframework_tests;'; fi"

script: phpunit --configuration phpunit_$DB.xml

notifications:
  recipients:
    - james@jamesking56.co.uk
  on_success: change
  on_failure: always